#!/usr/bin/env bash
# Regression suite for block-mainnet-broadcast.sh. Run from the repo root: bash .claude/hooks/test-guard.sh
H="$(dirname "$0")/block-mainnet-broadcast.sh"; pass=0; fail=0
t(){ r=$(printf '%s' "$2" | jq -Rs '{tool_input:{command:.}}' | bash "$H" 2>/dev/null; echo $?); r=${r##*$'\n'}
     if [[ $r == "$1" ]]; then pass=$((pass+1)); else fail=$((fail+1)); echo "FAIL expected=$1 got=$r: $2"; fi; }
B=('arc-forge script script/Deploy.s.sol --rpc-url arc --broadcast' 'cast send 0x36 x' 'arc-cast send 0xabc x' 'cast s 0x1 x' 'cast m 0x1 x' 'cast p 0x' 'cast w s x' 'cast w dk k' 'cast wallet decrypt-keystore k' 'cast wallet private-key' 'cast erc20 transfer 0x1 0x2 1' 'cast rpc eth_sendRawTransaction 0x' 'cast --json send 0x1 x' '~/.foundry/bin/cast send 0x1 x' 'bash -c "cast send 0x1 x"' 'echo send | xargs cast' 'c=cast; $c send 0x1' '${CAST} send 0x1' 'forge script X --resume' 'forge test --ffi' 'FOUNDRY_FFI=true forge test' 'forge create src/A.sol:A' 'export NETWORK="mainnet"; node x' "NETWORK='mainnet' node x" 'node scripts/cctp/base-sepolia-to-arc.ts' 'bash script/deploy-morpho-target.sh' 'python3 -c "open(\".env\")"' 'xxd .env' 'source .env && echo $PRIVATE_KEY' 'cat .env.local' 'cat keystores/x' 'cat ~/.foundry/keystores/dep' 'ls UTC--2026' 'cast wallet address --account dep --password-file p' 'git push origin +main' 'git push --mirror' 'git -C . push --force' 'git push -f' 'cast send $V x --unlocked --rpc-url https://rpc.mainnet.arc.io' 'forge script X --private-key 0xdead' 'forge script X --ledger --broadcast')
A=('cast call 0x8E35 "sendAssetsGate()(address)" --rpc-url https://rpc.mainnet.arc.io' 'cast calldata "deposit(uint256,address)" 100000000 0x1' 'cast sig "setSendSharesGate(address)"' 'cast nonce 0x1 --rpc-url x' 'cast compute-address 0x1 --nonce 3' 'cast block-number --rpc-url x' 'cast to-hex 101000000000000000000' 'cast code 0x1 --rpc-url x' 'arc-forge script script/Deploy.s.sol --rpc-url arc_mainnet --sender 0x1' 'arc-forge test --isolate --fork-url https://rpc.mainnet.arc.io' 'forge test -vv' 'cat .env.example' 'git push origin feat/mainnet-guards' 'git commit -m "feat(cctp): cast send --async, NETWORK=mainnet required"' 'grep -rn "testnet only" README.md' 'git diff --cached | grep -nEf .claude/secret-patterns.txt' 'git diff --cached' 'ls broadcast/Deploy.s.sol/' 'echo $HOME' 'cast call $VAULT "totalAssets()(uint256)" --rpc-url $ARC')
for c in "${B[@]}"; do t 2 "$c"; done; for c in "${A[@]}"; do t 0 "$c"; done
r=$(printf 'not json' | bash "$H" 2>/dev/null; echo $?); [[ $r == 2 ]] && pass=$((pass+1)) || { fail=$((fail+1)); echo "FAIL invalid JSON must block"; }
r=$(printf '{"tool_input":{"command":"ls"}}' | env PATH=/nonexistent /bin/bash "$H" 2>/dev/null; echo $?); [[ $r == 2 ]] && pass=$((pass+1)) || { fail=$((fail+1)); echo "FAIL missing jq must block"; }
echo "pass=$pass fail=$fail"; [[ $fail == 0 ]]
